version: 2.1

# For our CI/CD  Rollback Pipeline for us to fail & recover with grace

#notice our commands (looks like a job) to destroy aws stack
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID}

        # if get a Non-Zero i e 1 , destroy env      
      - run: return 1
      - destroy_environment
        when: on_fail

workflows:
  my_workflow:
    #Recover with grace meaning Rebuid the job
    jobs:
      - build