Resources:
    # This would be for a CI/CD  Rollback 
    Ec2Instance:
      Type: 'AWS::EC2::Instance'
      Properties:
        SecurityGroups:
          - !Ref InstanceSecurityGroup
        KeyName: Add-Yours-Here
        ImageId: 'ami-068663a3c619dd892'
    InstanceSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: Enable SSH access via port 22
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0

